# Generated by Django 2.0.5 on 2018-07-02 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('treated_subtitle_part', models.TextField(blank=True, null=True)),
                ('content1', models.TextField(blank=True, null=True)),
                ('content2', models.TextField(blank=True, null=True)),
                ('content3', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['uf', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GloboVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('globo_id', models.IntegerField(blank=True, null=True)),
                ('video_info', models.TextField(blank=True, null=True)),
                ('exhibited_at', models.DateField(blank=True, null=True)),
                ('subtitle_url', models.CharField(max_length=255)),
                ('subtitle_content', models.TextField(blank=True, null=True)),
                ('subtitle_cleaned_content', models.TextField(blank=True, null=True)),
                ('error_on_clean', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.GloboVideo'),
        ),
    ]
